#### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [8]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(np.all(x))

x = np.array([0,1,2])
print(np.all(x))

True
False


#### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [17]:
x = np.array([1, 0, 0, 0])
print(np.any(x))

x = np.array([0, 0, 0])
print(np.any(x))

True
False


#### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 

In [32]:
x = np.array([1, 2, 3, 5])
y = np.array([1, 2, 3, 4.8])

z=[True if x[i]==y[i] else False for i in range(len(x))]
print(z)

w=[True if (x[i]<=y[i]+0.5 and x[i]>=y[i]-0.5) else False for i in range(len(x))]
print(w)

[True, True, True, False]
[True, True, True, True]


#### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [34]:
zeros = np.zeros(10)
ones = np.ones(10)
x = np.full(10,5)
y = np.concatenate((zeros, ones, x))
print(y)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


#### 5. Write a NumPy program to create an array of the integers from 30 to70.

In [36]:
x=np.arange(30,71)
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

#### 6. Write a NumPy program to create a 3x3 identity matrix 

In [42]:
i=np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 7. Write a NumPy program to generate a random number between 0 and 1 

In [45]:
np.random.rand()

0.4910880190952722

#### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [46]:
np.random.randn(15)

array([ 1.61363449, -0.37526351,  1.53435721, -0.44925308,  0.89397029,
        1.64950709,  0.21645195, -0.23182005,  0.72061883,  0.56446264,
        0.57124546,  1.46830368, -1.22594008, -0.53145806,  0.92776843])

#### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [47]:
x=np.arange(15,56)
print(x[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


#### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [48]:
np.random.randint(0,11,5)

array([0, 7, 4, 6, 2])

#### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [51]:
x=np.zeros([10,10])
x[0,:]=1
x[-1,:]=1
x[:,0]=1
x[:,-1]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [53]:
x=np.zeros([5,5])
np.fill_diagonal(x,[1,2,3,4,5])
x

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

#### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [55]:
x=np.zeros([4, 4])
x[::2, 1::2]=1
x[1::2, ::2]=1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

#### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.


In [60]:
x=np.array([1,2,3,4])
y=np.array([4,3,2,1])
np.savez_compressed("array.npz",array1=x,array2=y)
z = np.load("array.npz")
arr1=z["array1"]
arr2=z["array2"]
print(arr1)
print(arr2)

[1 2 3 4]
[4 3 2 1]


#### 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select 

In [86]:
np.random.rand(40)

array([0.83091148, 0.78640876, 0.31219369, 0.20075916, 0.8731352 ,
       0.48176752, 0.36550068, 0.65360949, 0.08971725, 0.34044944,
       0.35285666, 0.44881661, 0.41616982, 0.91184894, 0.24248003,
       0.75391067, 0.26385127, 0.82967916, 0.79168174, 0.74133165,
       0.92922423, 0.70479581, 0.07999191, 0.59416648, 0.36929834,
       0.00894261, 0.3354902 , 0.78681565, 0.69630549, 0.56767809,
       0.16998658, 0.43022753, 0.70362516, 0.36576417, 0.20148857,
       0.76272387, 0.49521087, 0.46119756, 0.58783021, 0.16057515])

### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [90]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=x<4
z=x>4
equal= x==4
print(x[y])
print(x[z])
print(x[equal])

[1 2 3]
[5 6 7 8 9]
[4]
